sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - postgresql
  - docker
  - memcached
  - redis-server

install:
  - "sudo apt-get update"
  - "sudo apt-get -y install mysql-server"

before_script:
  - composer install
  - mysql -u root -e 'create database joomla_ut;'
  - mysql -u root joomla_ut < tests.phpunit/unit/schema/mysql.sql
  - psql -c 'create database joomla_ut;' -U postgres
  - psql -d joomla_ut -a -f tests.phpunit/unit/schema/postgresql.sql
  - if [ $TRAVIS_PHP_VERSION != "7.0" ]; then phpenv config-add build/travis/phpenv/memcached.ini; fi
  - if [ $TRAVIS_PHP_VERSION != "7.0" ]; then phpenv config-add build/travis/phpenv/redis.ini; fi

script:
  - libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
  - cd tests/acceptance; ./runtests.sh
  - if [ $TRAVIS_PHP_VERSION != "7.0" ]; then libraries/vendor/bin/phpcs --report=full --extensions=php --ignore=tests.phpunit -p --standard=build/phpcs/Joomla .; fi

branches:
  except:
    - 2.5.x
